driver: "px4"
local_planner:
  max_linear_velocity: 2.0        # m/s
  max_linear_acceleration: 1.0   # m/s²
  max_angular_velocity: 1.5      # rad/s
  max_angular_acceleration: 0.8  # rad/s²
  max_vertical_velocity: 0.5     # m/s
  max_vertical_acceleration: 0.2 # m/s²
  time_step: 0.05                # s
  land_descent_velocity: 0.4     # m/s, velocidad constante de descenso en aterrizaje
